source 'https://rubygems.org'

gem 'fluentd', '~>0.12.32'
gem 'activesupport', '~>4.2.6'
gem 'fluent-plugin-kubernetes_metadata_filter', '~>0.27.0'
gem 'fluent-plugin-systemd', '~>0.0.8'
gem 'aws-sdk-core', '~> 2.0'
gem 'fluent-plugin-cloudwatch-logs', '~>0.4.0'
gem 'oj', '~>2.18.1'
